# Instructions for Completing the Jupyter Notebook Assignment

---

## 1. Download the Jupyter Notebook

* First, download the provided Jupyter Notebook file (`.ipynb`) to your computer.
* Make sure you save it in a location you can easily find, such as your Desktop or a dedicated course folder.

---

## 2. Understand the Rules for Modifying the Notebook

* Some cells in the notebook are marked with a **`# Do not modify`** comment.
* **Important:**

  * You are **not allowed** to change the content of these cells.
  * You are only expected to **run them**.
* Do **not delete any existing cells** in the notebook.
* Do **not create any new cells**.

### Writing Your Answers

When you are writing your own answers in the designated answer cells:

1. **First clear the entire content of the answer cell.**
2. Always start your answer with the line:

```python
%%sql results <<
```

3. On the **next line**, write your SQL query.

**Example format:**

```python
%%sql results <<
SELECT *
FROM customers;
```

---

## 3. Testing Your Queries

* The notebook provides a SQL **CREATE script** that defines the database and tables you’ll be working with.
* To practice or debug your SQL queries, you may copy this script and paste it into the online tool:
  👉 [SQLiteViz](https://sqliteviz.com/app/#/workspace)
* In SQLiteViz, you can run your queries, check the results, and once you are confident the output matches expectations, copy your final query back into the notebook in the correct answer cell.

---

## 4. Expected Output vs. Your Output

* For each question, there are two output sections in the notebook:

  1. **Expected Output:** Shows you what the correct result should look like.
  2. **Your Output:** Shows what your query actually produces.
* Your result must match the expected output **exactly**. This includes:

  * Column names
  * Row order (if specified)
  * Spacing
  * Capitalization (case sensitivity matters)
* Even a small difference will cause your answer to be marked as incorrect.

---

## 5. Using the Assert Cells

* After writing your query in the answer cell, scroll down to the corresponding **assert cell**.
* Run the assert cell.
* If you see **no error message**, your answer is correct. 🎉
* If you see an error message, it means your query does not exactly match the expected output.

  * In that case, go back, fix your SQL query, and rerun the assert cell until it passes.

---

## 6. Final Steps

Once you have completed all the questions and all assert cells run without errors:

1. Rename your notebook file to your **email address** (e.g., `studentname@email.com.ipynb`).
2. Double-check that the file still ends with the `.ipynb` extension.
3. Upload the completed notebook to the submission form provided.

---

✅ Following these steps carefully will ensure your work is valid and can be graded without issues.

# DO NOT ADD OR CREATE ANY NEW CELLS
## DO NOT ADD OR CREATE ANY NEW CELLS
### DO NOT ADD OR CREATE ANY NEW CELLS
#### DO NOT ADD OR CREATE ANY NEW CELLS

### YOU HAVE TO RUN ALL THESE CELLS BEFORE MOVING ON TO YOUR QUESTIONS. IF YOU ENCOUNTER ANY ERRORS JUST RESTART THE KERNEL

In [1]:
#Do not modify this cell
#Run this Cell
import pandas as pd
%load_ext sql
%config SqlMagic.style = 'PLAIN_COLUMNS'

#### Do not modify the cell below in any way. You are required to only run it and move on.

In [3]:
%%sql sqlite://
-- Do not modify this cell
CREATE TABLE Sales (
    OrderID INT PRIMARY KEY,
    ProductName VARCHAR(50),
    Customer VARCHAR(50),
    OrderDate DATE,
    Quantity INT,
    UnitPrice INT
);
INSERT INTO Sales (OrderID, ProductName, Customer, OrderDate, Quantity, UnitPrice)
VALUES
    (1, 'Product A', 'David', '2024-01-05', 3, 25),
    (2, 'Product B', 'Bianca', '2024-01-10', 2, 30),
    (3, 'Product C', 'Leslie', '2024-01-15', 1, 15),
    (4, 'Product A', 'David', '2024-01-20', 4, 25),
    (5, 'Product D', 'Simon', '2024-01-25', 2, 50),
    (6, 'Product B', 'Bianca', '2024-02-01', 3, 30),
    (7, 'Product C', 'Simon', '2024-02-05', 1, 15),
    (8, 'Product A', 'Kean', '2024-02-10', 5, 25),
    (9, 'Product D', 'Kean', '2024-02-15', 2, 50),
    (10, 'Product B', 'Bianca', '2024-02-20', 2, 30);

Done.
10 rows affected.

[]

#### Do not modify the cell below in any way. You are required to only run it and move on.

In [5]:
data = {
    'OrderID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'ProductName': ['Product A', 'Product B', 'Product C', 'Product A', 'Product D',
                    'Product B', 'Product C', 'Product A', 'Product D', 'Product B'],
    'Customer': ['David', 'Bianca', 'Leslie', 'David', 'Simon',
                     'Bianca', 'Simon', 'Kean', 'Kean', 'Bianca'],
    'OrderDate': ['2024-01-05', '2024-01-10', '2024-01-15', '2024-01-20', '2024-01-25',
                  '2024-02-01', '2024-02-05', '2024-02-10', '2024-02-15', '2024-02-20'],
    'Quantity': [3, 2, 1, 4, 2, 3, 1, 5, 2, 2],
    'UnitPrice': [25, 30, 15, 25, 50, 30, 15, 25, 50, 30]
}

# Create DataFrame
sales_data = pd.DataFrame(data)

In [7]:
#run this cell to see what the dataset looks like
#do not modify this cell
sales_data

   OrderID ProductName Customer   OrderDate  Quantity  UnitPrice
0        1   Product A    David  2024-01-05         3         25
1        2   Product B   Bianca  2024-01-10         2         30
2        3   Product C   Leslie  2024-01-15         1         15
3        4   Product A    David  2024-01-20         4         25
4        5   Product D    Simon  2024-01-25         2         50
5        6   Product B   Bianca  2024-02-01         3         30
6        7   Product C    Simon  2024-02-05         1         15
7        8   Product A     Kean  2024-02-10         5         25
8        9   Product D     Kean  2024-02-15         2         50
9       10   Product B   Bianca  2024-02-20         2         30

# Here are your questions
- The name of the table is sales
- Always start your answers with this line `%%sql result <<`
- Then start writing your query on the next line for example
    ```
%%sql result <<
    select * from sales
    ```

- If you do not follow these instructions your score will not count.

#### 1. Retrieve all orders made by a customer named Bianca.
- Just use `*` to get all the column names
- clear everything in the cell below and write your sql query there. 
**Remember to Follow the Instructions on how to write your query**
- the first line in your cell must be ```%%sql result <<```

In [9]:
%%sql result <<
SELECT *
FROM sales
WHERE Customer = 'Bianca';

 * sqlite://
Done.
Returning data to local variable result

In [11]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
result.DataFrame()

This is the output of your query

   OrderID ProductName Customer   OrderDate  Quantity  UnitPrice
0        2   Product B   Bianca  2024-01-10         2         30
1        6   Product B   Bianca  2024-02-01         3         30
2       10   Product B   Bianca  2024-02-20         2         30

In [13]:
#Run this cell to see the expected output
#do not modify this cell
test1 = sales_data[sales_data['Customer'] == 'Bianca'].reset_index(drop=True)
print('This is the expected output')
test1

This is the expected output

   OrderID ProductName Customer   OrderDate  Quantity  UnitPrice
0        2   Product B   Bianca  2024-01-10         2         30
1        6   Product B   Bianca  2024-02-01         3         30
2       10   Product B   Bianca  2024-02-20         2         30

In [15]:
#do not modify this cell
assert result.DataFrame().equals(test1)

#### 2. Retrieve all products and the total qunatities sold for each product.
- Use the alias `total_quantity` for your aggregate column. Spell it exactly as i have written it.
- clear everything in the cell below and write your sql query there. 
**Remember to Follow the Instructions on how to write your query**
- the first line in your cell must be ```%%sql result <<```

In [17]:
%%sql result <<
SELECT ProductName, SUM(Quantity) AS total_quantity
FROM sales
GROUP BY ProductName;

 * sqlite://
Done.
Returning data to local variable result

In [19]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
result.DataFrame()

This is the output of your query

  ProductName  total_quantity
0   Product A              12
1   Product B               7
2   Product C               2
3   Product D               4

In [21]:
#Run this cell to see the expected output
#do not modify this cell
test2 = sales_data.groupby('ProductName')['Quantity'].sum().reset_index()
test2.columns = ['ProductName', 'total_quantity']
print('This is the expected output')
test2

This is the expected output

  ProductName  total_quantity
0   Product A              12
1   Product B               7
2   Product C               2
3   Product D               4

In [23]:
#do not modify this cell
assert result.DataFrame().equals(test2)

#### 3. Write a query that Calculate the total quantity sold from sales in January 2024 only.
- Use the alias `total_quantity` for your aggregate column. Spell it exactly as i have written it.
- clear everything in the cell below and write your sql query there. 
**Remember to Follow the Instructions on how to write your query**
- the first line in your cell must be ```%%sql result <<```

In [25]:
%%sql result <<
SELECT SUM(Quantity) AS total_quantity
FROM sales
WHERE OrderDate >= '2024-01-01' AND OrderDate <= '2024-01-31';

 * sqlite://
Done.
Returning data to local variable result

In [27]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
result.DataFrame()

This is the output of your query

   total_quantity
0              12

In [29]:
#Run this cell to see the expected output
#do not modify this cell
jan_quantity = (sales_data[(sales_data['OrderDate'] >= '2024-01-01') & (sales_data['OrderDate'] <= '2024-01-31')]['Quantity'].sum())
test3 = pd.DataFrame([jan_quantity], columns = ['total_quantity'])
print('This is the expected output')
test3

This is the expected output

   total_quantity
0              12

In [31]:
#do not modify this cell
assert result.DataFrame().equals(test3)

#### 4. Write a query that Calculates the average unit price sold.
- Use the alias `average_price` for your aggregate column. Spell it exactly as i have written it.
- clear everything in the cell below and write your sql query there. 
**Remember to Follow the Instructions on how to write your query**
- the first line in your cell must be ```%%sql result <<```

In [33]:
%%sql result <<
SELECT AVG(UnitPrice) AS average_price
FROM sales;

 * sqlite://
Done.
Returning data to local variable result

In [35]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
result.DataFrame()

This is the output of your query

   average_price
0           29.5

In [37]:
#Run this cell to see the expected output
#do not modify this cell
avgprc = sales_data['UnitPrice'].mean()
test4 = pd.DataFrame([avgprc], columns = ['average_price'])
print('This is the expected output')
test4

This is the expected output

   average_price
0           29.5

In [39]:
#do not modify this cell
assert result.DataFrame().equals(test4)

#### 5. Retrieve a list of customers who made more than 2 orders.
- Use the alias `order_count` for your aggregate column. Spell it exactly as i have written it.
- clear everything in the cell below and write your sql query there. 
**Remember to Follow the Instructions on how to write your query**
- the first line in your cell must be ```%%sql result <<```

In [41]:
%%sql result <<
SELECT Customer, COUNT(OrderID) AS order_count
FROM sales
GROUP BY Customer
HAVING order_count > 2;

 * sqlite://
Done.
Returning data to local variable result

In [43]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
result.DataFrame()

This is the output of your query

  Customer  order_count
0   Bianca            3

In [45]:
#Run this cell to see the expected output
#do not modify this cell
test5 = (sales_data.groupby('Customer')
                                     .size()
                                     .reset_index(name='order_count')
                                     .query('order_count > 2'))
print('This is the expected output')
test5

This is the expected output

  Customer  order_count
0   Bianca            3

In [47]:
#do not modify this cell
assert result.DataFrame().equals(test5)